[package]
name = "golem-cli"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud/"
repository = "https://github.com/golemcloud/golem-cli"
description = "Command line interface for Golem."
autotests = false
build = "build.rs"

[features]
default = []
server-commands = []

[lib]
harness = false

[[bin]]
name = "golem-cli"
path = "src/main.rs"
test = false

[[test]]
name = "integration"
path = "tests/lib.rs"
test = true
harness = false

[dependencies]
# Workspace deps
golem-templates = { path = "../golem-templates", version = "=0.0.0" }

# Golem deps
golem-client = { workspace = true }
golem-cloud-client = { workspace = true }
golem-common = { workspace = true }
golem-rib = { workspace = true }
golem-rib-repl = { workspace = true }
golem-wasm-ast = { workspace = true }
golem-wasm-rpc = { workspace = true }
golem-wit = { workspace = true }

# External deps
anyhow = { workspace = true }
assert2 = { workspace = true }
async-trait = { workspace = true }
async_zip = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
cargo-component = { workspace = true }
cargo-component-core = { workspace = true }
cargo_toml = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap-verbosity-flag = { workspace = true }
clap_complete = { workspace = true }
cli-table = { workspace = true }
colored = { workspace = true }
dirs = { workspace = true }
envsubst = { workspace = true }
fs_extra = { workspace = true }
futures-util = { workspace = true }
fuzzy-matcher = { workspace = true }
heck = { workspace = true }
humansize = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
inquire = { workspace = true }
iso8601 = { workspace = true }
itertools = { workspace = true }
lenient_bool = { workspace = true }
log = { workspace = true }
minijinja = { workspace = true }
native-tls = { workspace = true }
phf = { workspace = true }
pretty_env_logger = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shadow-rs = { workspace = true }
shlex = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
syn = { workspace = true }
tempfile = { workspace = true }
terminal_size = { workspace = true }
textwrap = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
version-compare = { workspace = true }
wac-graph = { workspace = true }
walkdir = { workspace = true }
wasm-metadata = { workspace = true }
wasm-wave = { workspace = true }
wax = { workspace = true }
wit-bindgen-rust = { workspace = true }
wit-encoder = { workspace = true }
wit-parser = { workspace = true }

[dev-dependencies]

# External deps
axum = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde_json_path = { workspace = true }
strip-ansi-escapes = { workspace = true }
test-r = { workspace = true }
wasm-metadata = { workspace = true }

[build-dependencies]
shadow-rs = { workspace = true }
