[package]
name = "golem-wasm-rpc-stubgen"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem-cli"
description = "Golem WASM RPC stub generator"

autotests = false

[lib]
path = "src/lib.rs"
harness = false

[[test]]
name = "integration"
path = "tests/lib.rs"
harness = false

[dependencies]
golem-wasm-ast = { workspace = true }
golem-wasm-rpc = { workspace = true }
golem-wit = { workspace = true }

anyhow = { workspace = true }
blake3 = { workspace = true }
cargo-component = { workspace = true }
cargo-component-core = { workspace = true }
cargo_toml = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
envsubst = { workspace = true }
fs_extra = { workspace = true }
heck = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
minijinja = { workspace = true }
pretty_env_logger = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shlex = { workspace = true }
syn = { workspace = true }
tempfile = { workspace = true }
terminal_size = { workspace = true }
textwrap = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
wac-graph = { workspace = true }
walkdir = { workspace = true }
wax = { workspace = true }
wit-bindgen-rust = { workspace = true }
wit-encoder = { workspace = true }
wit-parser = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
test-r = { workspace = true }
