name: "Desktop CI"

on:
  pull_request:
    paths:
    - "desktop-app/**"
    - ".github/workflows/desktop-ci.yaml"
  push:
    branches:
    - main
    tags:
    - "v*.*.*"
    paths:
    - "desktop-app/**"
    - ".github/workflows/desktop-ci.yaml"

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: macos-latest
          target: aarch64-apple-darwin
        - platform: macos-latest
          target: x86_64-apple-darwin
        - platform: ubuntu-22.04
          target: ""
        - platform: windows-latest
          target: ""

    # Run on the appropriate runner for each platform
    runs-on: ${{ matrix.platform == 'ubuntu-22.04' && 'blacksmith' || matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target != '' && matrix.target || '' }}

    - name: Setup Rust cache (Ubuntu)
      if: matrix.platform == 'ubuntu-22.04'
      uses: useblacksmith/rust-cache@v3
      with:
        workspaces: "./desktop-app/src-tauri -> target"

    - name: Setup Rust cache (macOS and Windows)
      if: matrix.platform != 'ubuntu-22.04'
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "./desktop-app/src-tauri -> target"

    - name: Install dependencies (Ubuntu only)
      if: matrix.platform == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Install frontend dependencies
      run: npm install --force
      working-directory: ./desktop-app

    - name: Build Tauri apps
      id: tauri-build
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: ${{ matrix.target != '' && format('--target {0}', matrix.target) || '' }}
        projectPath: "./desktop-app"

    # macOS specific artifacts uploads
    - name: Upload macOS DMG artifact
      if: matrix.platform == 'macos-latest' && matrix.target != ''
      uses: actions/upload-artifact@v4
      with:
        name: GolemDesktop-${{ matrix.target }}-dmg
        path: ./desktop-app/src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
        if-no-files-found: ignore

    - name: Upload macOS App artifact
      if: matrix.platform == 'macos-latest' && matrix.target != ''
      uses: actions/upload-artifact@v4
      with:
        name: GolemDesktop-${{ matrix.target }}-app
        path: ./desktop-app/src-tauri/target/${{ matrix.target }}/release/bundle/macos/*.app
        if-no-files-found: ignore

    # Linux specific artifacts uploads
    - name: Upload Linux AppImage artifact
      if: matrix.platform == 'ubuntu-22.04'
      uses: actions/upload-artifact@v4
      with:
        name: GolemDesktop-linux-appimage
        path: ./desktop-app/src-tauri/target/release/bundle/appimage/*.AppImage
        if-no-files-found: ignore

    - name: Upload Linux Deb artifact
      if: matrix.platform == 'ubuntu-22.04'
      uses: actions/upload-artifact@v4
      with:
        name: GolemDesktop-linux-deb
        path: ./desktop-app/src-tauri/target/release/bundle/deb/*.deb
        if-no-files-found: ignore

    - name: Upload Linux RPM artifact
      if: matrix.platform == 'ubuntu-22.04'
      uses: actions/upload-artifact@v4
      with:
        name: GolemDesktop-linux-rpm
        path: ./desktop-app/src-tauri/target/release/bundle/rpm/*.rpm
        if-no-files-found: ignore

    # Windows specific artifacts uploads
    - name: Upload Windows MSI artifact
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: GolemDesktop-windows-msi
        path: ./desktop-app/src-tauri/target/release/bundle/msi/*.msi
        if-no-files-found: ignore

    - name: Upload Windows EXE artifact
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: GolemDesktop-windows-exe
        path: ./desktop-app/src-tauri/target/release/bundle/nsis/*.exe
        if-no-files-found: ignore
