name: "Desktop CI"

on:
  pull_request:
    paths:
    - "desktop-app/**"
    - ".github/workflows/desktop-ci.yaml"
  push:
    branches:
    - main
    # TODO: Tag and publishing is not enabled until merging history
    # tags:
    # - "v*.*.*"
    paths:
    - "desktop-app/**"
    - ".github/workflows/desktop-ci.yaml"

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: macos-latest
          target: aarch64-apple-darwin
        - platform: macos-latest
          target: x86_64-apple-darwin
        - platform: ubuntu-22.04
          target: ""
        - platform: windows-latest
          target: ""

    # Run on the appropriate runner for each platform
    runs-on: ${{ matrix.platform == 'ubuntu-22.04' && 'blacksmith' || matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target != '' && matrix.target || '' }}

    - name: Setup Rust cache (Ubuntu)
      if: matrix.platform == 'ubuntu-22.04'
      uses: useblacksmith/rust-cache@v3
      with:
        workspaces: "./desktop-app/src-tauri -> target"

    - name: Setup Rust cache (macOS and Windows)
      if: matrix.platform != 'ubuntu-22.04'
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "./desktop-app/src-tauri -> target"

    - name: Install dependencies (Ubuntu only)
      if: matrix.platform == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Install frontend dependencies
      run: npm install --force
      working-directory: ./desktop-app

    - name: Build Tauri apps
      id: tauri-build
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: ${{ matrix.target != '' && format('--target {0}', matrix.target) || '' }}
        projectPath: "./desktop-app"

    - name: Upload artifacts
      if: startsWith(github.ref, 'refs/tags/') # commented out for now to test the artifact upload
      uses: actions/upload-artifact@v4
      with:
        name: golem-app-${{ matrix.platform }}-${{ matrix.target || 'default' }}
        path: |
          ./desktop-app/src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
          ./desktop-app/src-tauri/target/${{ matrix.target }}/release/bundle/macos/*.app
          ./desktop-app/src-tauri/target/release/bundle/appimage/*.AppImage
          ./desktop-app/src-tauri/target/release/bundle/deb/*.deb
          ./desktop-app/src-tauri/target/release/bundle/rpm/*.rpm
          ./desktop-app/src-tauri/target/release/bundle/msi/*.msi
          ./desktop-app/src-tauri/target/release/bundle/nsis/*.exe
